# Generated by Django 4.1.7 on 2023-02-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_location_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='state',
            new_name='areas',
        ),
    ]
