# Generated by Django 4.1.7 on 2023-02-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
